Update README.md
huggingface/hfcc.nvim pull request #8
Opened 2023-05-14 05:26 UTC by cxwx

add vim-plug

2023-05-14 14:45 UTC, McPatate requested changes
Small nits, thanks for contributing !

Does this fix #7 ?

2023-05-14 14:45 UTC, McPatate commented on README.md
> +### Using [vim-plug](https://github.com/folke/lazy.nvim)
```suggestion
### Using [vim-plug](https://github.com/junegunn/vim-plug)
```

2023-05-14 14:45 UTC, McPatate commented on README.md
> +Plug 'https://github.com/huggingface/hfcc.nvim'
```suggestion
Plug 'huggingface/hfcc.nvim'
```

2023-05-14 14:45 UTC, McPatate commented on README.md
> +      })
```suggestion
require('hfcc').setup({
  api_token = "<insert your api token here>",
  model = "bigcode/starcoder" -- can be a model ID or an http endpoint
})
```

2023-05-14 18:07 UTC, McPatate commented on README.md
> +      })
Removing the `api_token` option as this is not the recommended way to authenticate anymore, cf #11

2023-05-15 04:45 UTC, cxwx commented
> Small nits, thanks for contributing !
> 
> Does this fix #7 ?

yes

2023-05-15 08:25 UTC, merged